version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true #コンテナを起動させ続けることができる


  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true #コンテナを起動させ続けることができる
    stdin_open: true
    depends_on:
      - db
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/myproject
volumes:
  postgresql-data:
    driver: local

# version: '3'
# services:
#   db:
#     image: postgres
#     environment:
#       POSTGRES_PASSWORD: password
#     ports:
#       - '5432:5432'
#     volumes:
#       - postgresql-data:/var/lib/postgresql/data
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     command: bundle exec rails s -p 3000 -b '0.0.0.0'
#     tty: true
#     stdin_open: true
#     depends_on:
#       - db
#     links:
#       - db
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/myproject
# volumes:
#   postgresql-data:
#     driver: local
